In [1]:
import numpy as np
print("successfully")

successfully


In [4]:
np.__version__

'1.26.4'

In [5]:
lst=list(range(1,25))
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [6]:
arr=np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [7]:
print(type(lst))

<class 'list'>


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr1=np.array([25,10,20,30,40,50,60])
arr1

array([25, 10, 20, 30, 40, 50, 60])

* 2D ARRAY

In [12]:
arr_2d=np.array([[10,20],[30,40],[40,50]])
arr_2d

array([[10, 20],
       [30, 40],
       [40, 50]])

In [16]:
arr_3d=np.array([[10,20,3],[4,30,40],[4,40,50]])
arr_3d

array([[10, 20,  3],
       [ 4, 30, 40],
       [ 4, 40, 50]])

In [18]:
print(type(arr_3d))

<class 'numpy.ndarray'>


In [20]:
rr_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],    # First 3x3 matrix
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]  # Second 3x3 matrix
])

print(rr_3d)  


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [21]:
print("Shape of array:",rr_3d.shape)

Shape of array: (2, 3, 3)


In [23]:
arr_2dd=np.ones((3,4))
arr_2dd

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
arrr=np.zeros((3,3))
arrr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arrrr=np.linspace(1,10,5)
arrrr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
arr=np.array([1,2,3,4,5,6])
reshapes_arr=arr.reshape(2,3)
print(arr)
print(reshapes_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [29]:
arr=np.arange(1,31)
reshapes_arr=arr.reshape(5,6)
print(arr)
print(reshapes_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [32]:
#arrange 1 to 30 into reshaped_arr for 3D
arr = np.arange(1, 31)

reshaped_arr = arr.reshape(5, 6,1)

print(reshaped_arr)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]
  [17]
  [18]]

 [[19]
  [20]
  [21]
  [22]
  [23]
  [24]]

 [[25]
  [26]
  [27]
  [28]
  [29]
  [30]]]


In [33]:
arr =  np.random.randint(1,10,5)
arr

array([2, 8, 6, 4, 2])

In [34]:
arr = np.random.randint(1,5,(3,3,3))
arr

array([[[1, 1, 3],
        [1, 2, 3],
        [1, 1, 4]],

       [[1, 1, 2],
        [3, 3, 4],
        [3, 4, 4]],

       [[2, 3, 3],
        [3, 3, 1],
        [1, 4, 3]]])

In [35]:
arr= np.random.random(10)
arr

array([0.82560357, 0.22868763, 0.22398862, 0.9976504 , 0.73449179,
       0.51283511, 0.70375514, 0.90412219, 0.87499532, 0.60033884])

In [36]:
random_2d = np.random.randint(1, 100, (3, 4))  # Random integers between 1 and 100

print("2D Random Array:")
print(random_2d)

2D Random Array:
[[91 80 17 31]
 [98  9 16 32]
 [25 59 44 23]]


In [37]:
# Generate a 3D array with random numbers (size: 2x3x4)
random_3d = np.random.randint(1, 100, (2, 3, 4))

print("\n3D Random Array:")
print(random_3d)


3D Random Array:
[[[35 94 83 14]
  [78 57 41  8]
  [ 7 83 24 58]]

 [[ 2 10 76 33]
  [59 93 88 90]
  [62 13 24 10]]]


In [39]:
arr= np.arange(60).reshape(10,6)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(arr.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]
int32
2
60
(10, 6)


In [40]:
my_list = [1, 2, 3, 4, 5]

# Convert the list into a NumPy array
my_array = np.array(my_list)#for conversion of list to array

print(my_array)

[1 2 3 4 5]


In [41]:
# Create an array with shape (2, 3)
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
arr = np.transpose(arr)
print(arr)

[[1 4]
 [2 5]
 [3 6]]
