In [121]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [122]:
import numpy as np

In [123]:
lst=[1,2,3,4,'ab','c','dfg']
lst

[1, 2, 3, 4, 'ab', 'c', 'dfg']

In [124]:
type(lst)

list

In [125]:
arr=np.array(lst)

In [126]:
arr

array(['1', '2', '3', '4', 'ab', 'c', 'dfg'], dtype='<U11')

In [127]:
type(arr)

numpy.ndarray

In [128]:
arr1=np.arange(1,25,2)
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [129]:
arr2=range(1,25,2)
print(list(arr2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23]


In [130]:
zer0=np.zeros(((2,2)))
zer0

array([[0., 0.],
       [0., 0.]])

In [131]:
ones=np.ones((10,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [132]:
ones.ndim

2

In [133]:
lin=np.linspace(1,25,10)   # 1 se 25 ke bich m 10 number with eqaul space 
lin

array([ 1.        ,  3.66666667,  6.33333333,  9.        , 11.66666667,
       14.33333333, 17.        , 19.66666667, 22.33333333, 25.        ])

In [134]:
arr3=np.arange(0,20).reshape(4,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [135]:
arr3=np.arange(0,20).reshape(4,5,1)
arr3

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [136]:
rarr=np.random.randint(20)
rarr

2

In [137]:
rarr1=np.random.randint(1,20,100)       # 1 se 20 ke bich m 100 number 
rarr1

array([ 8,  4, 15,  3, 13, 12, 12,  2, 18, 10, 12, 18, 10, 12, 19,  8,  1,
       19, 17, 15, 12, 11, 18, 14, 16,  4,  8, 14,  8, 12, 14, 14, 12,  7,
       17, 19,  9, 14,  7, 10,  5, 19, 18, 17,  3,  9, 18,  3,  7,  6, 19,
       19,  6, 15, 18,  5,  8,  9,  9, 17, 19,  1,  8,  9,  8, 17,  5, 13,
        1, 17,  7,  1,  1,  7,  6,  2, 16, 15, 17,  3, 11, 11,  5,  5,  1,
       15,  3, 14,  1, 17,  4, 19, 13,  3, 19, 14, 12,  3,  1,  4])

In [138]:
rarr1=np.random.randint(1,20,(2,4,3))       # n number generate krna 1 se 20 ke bich m 2 block 4 rows or 3 column
rarr1

array([[[15, 19,  1],
        [12, 18, 14],
        [19, 19,  8],
        [12,  3, 17]],

       [[12, 18, 17],
        [ 9,  2, 19],
        [10,  9,  5],
        [12,  4, 10]]])

In [139]:
arr2d=np.arange(100).reshape(2,50) #1d se 2,3,4d m convert krna
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [140]:
arr1d=arr2d.flatten() # nd se 1d m convert krna
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [141]:
arr1d=arr2d.ravel() # nd se 1d m convert krna
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [142]:
lst2d=[[1,2,3],[234,2,4]]
lst2d

[[1, 2, 3], [234, 2, 4]]

In [143]:
len(lst2d[0])

3

In [144]:
arr2d=np.array(lst2d)

In [145]:
arr2d

array([[  1,   2,   3],
       [234,   2,   4]])

In [146]:
arr2d.shape

(2, 3)

In [147]:
taa=np.transpose(arr2d)
taa

array([[  1, 234],
       [  2,   2],
       [  3,   4]])

In [148]:
arr=np.arange(0,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [149]:
arr[4:11:3]      # 4 se 10 tk aayega 3 ka gap hoga  array slicing

array([ 4,  7, 10])

In [150]:
arr=np.arange(0,100).reshape(20,5) # 1d se 2d se change ho gya
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [151]:
arr[1]

array([5, 6, 7, 8, 9])

In [152]:
arr[1][1]

6

In [153]:
arr[1,1]

6

In [154]:
arr[1:5]



array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [155]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [156]:
arr[14,2]

72

In [157]:
arr[-1,-1]

99

In [158]:
arr[:4,-1]

array([ 4,  9, 14, 19])

In [161]:
arr[0,1]=22 # replace value

In [162]:
arr

array([[22, 22, 22, 22, 22],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [167]:
arr1=arr.reshape(5,5,4)

In [170]:
arr1

array([[[22, 22, 22, 22],
        [22,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [168]:
arr1[:,0:1,0:1]

array([[[22]],

       [[20]],

       [[40]],

       [[60]],

       [[80]]])

In [169]:
arr1.ndim

3

In [176]:
arr1[2][1][2]*2

92

In [ ]:
arr1+2      # sare m +2 ho jayega

array([[[ 24,  24,  24,  24],
        [ 24,   7,   8,   9],
        [ 10,  11,  12,  13],
        [ 14,  15,  16,  17],
        [ 18,  19,  20,  21]],

       [[ 22,  23,  24,  25],
        [ 26,  27,  28,  29],
        [ 30,  31,  32,  33],
        [ 34,  35,  36,  37],
        [ 38,  39,  40,  41]],

       [[ 42,  43,  44,  45],
        [ 46,  47,  48,  49],
        [ 50,  51,  52,  53],
        [ 54,  55,  56,  57],
        [ 58,  59,  60,  61]],

       [[ 62,  63,  64,  65],
        [ 66,  67,  68,  69],
        [ 70,  71,  72,  73],
        [ 74,  75,  76,  77],
        [ 78,  79,  80,  81]],

       [[ 82,  83,  84,  85],
        [ 86,  87,  88,  89],
        [ 90,  91,  92,  93],
        [ 94,  95,  96,  97],
        [ 98,  99, 100, 101]]])

In [175]:
arr1*2

array([[[ 44,  44,  44,  44],
        [ 44,  10,  12,  14],
        [ 16,  18,  20,  22],
        [ 24,  26,  28,  30],
        [ 32,  34,  36,  38]],

       [[ 40,  42,  44,  46],
        [ 48,  50,  52,  54],
        [ 56,  58,  60,  62],
        [ 64,  66,  68,  70],
        [ 72,  74,  76,  78]],

       [[ 80,  82,  84,  86],
        [ 88,  90,  92,  94],
        [ 96,  98, 100, 102],
        [104, 106, 108, 110],
        [112, 114, 116, 118]],

       [[120, 122, 124, 126],
        [128, 130, 132, 134],
        [136, 138, 140, 142],
        [144, 146, 148, 150],
        [152, 154, 156, 158]],

       [[160, 162, 164, 166],
        [168, 170, 172, 174],
        [176, 178, 180, 182],
        [184, 186, 188, 190],
        [192, 194, 196, 198]]])

In [178]:
arr2=np.arange(100)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [183]:
arr3=np.arange(100)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [184]:
arr2+arr3

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [185]:
x=[1,2,3,4,5]
y=[4,5,6,7,8]
x,y

([1, 2, 3, 4, 5], [4, 5, 6, 7, 8])

In [190]:
x*y

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
x+y       # list m + join kr rha h not operation 

[1, 2, 3, 4, 5, 4, 5, 6, 7, 8]

In [188]:
xarr=np.array(x)
yarr=np.array(y)

In [ ]:
xarr+yarr      # array m element + huye addition huye h 

array([ 5,  7,  9, 11, 13])

In [191]:
xarr*yarr

array([ 4, 10, 18, 28, 40])

In [ ]:
# list m do list ke bich aritnetic operation nhi hote h 
# but array m ho jata h 